import type { Metadata } from "next";
import "./globals.css";
import Components from "@/components";

// https://www.figma.com/design/xwwVYs6vDFqLQ1UTKOEM1V/Personal-Portfolio--UI---UX-Designer--Free--Community-?m=auto&is-community-duplicate=1&fuid=1266444731379283932

//https://www.reactbits.dev/backgrounds/dot-grid

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className="dark nunito">
            <body className="antialiased max-w-screen overflow-hidden bg-dark text-white transition-colors duration-300">
                <Components>{children}</Components>
            </body>
        </html>
    );
}
